### ISSUE TITLE
Incorrect path

### ISSUE THREAD

**Issue by max7k** [noxify/sublime_hpsm#4]
When I load a script from SM using the HPSM menu (Tools - Command Palette - HPSM Scriptlibrary Menu -...), the path for the new file is incorrect:
![image](https://user-images.githubusercontent.com/2865891/45950595-27d04780-c009-11e8-85e7-75782434a9e0.png)

Meanwhile, the file is saved normally:
![image](https://user-images.githubusercontent.com/2865891/45950519-cb6d2800-c008-11e8-93d9-1ca04fc00a05.png)
and i can open it:
![image](https://user-images.githubusercontent.com/2865891/45950558-fc4d5d00-c008-11e8-9cac-c06b35edac72.png)

**Comment by noxify** [comment]
Hi,

Sorry for the delay.

Did you changed the path in the package/user settings? 

Can you paste your configuration so that I can try to reproduce it? 

Thanks!
